### ISSUE TITLE
Where do I put the MAC address?

### ISSUE THREAD

**Issue by andrei-lazarov** [klattimer/LGWebOSRemote#50]
All commands except 'lgtv on' work (simply typing them in Windows cmd) because it doesn't have the MAC address. I can't figure out where to write it.

**Comment by DarkCeptor44** [comment]
Hi, the MAC address should  be put in the config file, which is supposed to be in one of these three locations: `"/etc/lgtv/config.json"`, `"~/.lgtv/config.json"`, `"/opt/venvs/lgtv/config/config.json"`. If you're on Windows the `~/.lgtv` translates to `C:\Users\(User)\.lgtv`. Open the file, look for `"mac": null` and replace `null` by the MAC address.

Unfortunately for me I still can't turn my TV on even though I've already put the right address in.

**Comment by sobertram** [comment]
Not sure if you already solved your issues but I recently was able to get this to work for the basic on and off. First you need to make sure you run auth, not just to get the mac address but so that the tv can give your client computer access to the tv. I think doing auth creates a key that gets authenticated by the lgtv when you connect. Manually adding the mac address to the config file won't get you a proper key. And also make sure the TV is on the first time you do this because you will be prompted to accept the connection for it to work.

Also you need to give your tv a name and use that name in all communication. So for me I did "lgtv auth 192.168.88.250 lg1" where lg1 is the name I gave my tv.

I could then do "lgtv lg1 off" and "lgtv lg1 on".

When you run "on" it gives no feedback on the command line. When you do "off" you get the following output:

{"closing": {"code": 1000, "reason": ""}}

My tv is "model": "UK6300PUE".

**Comment by DarkCeptor44** [comment]
@sobertram That's right but some models just don't support Wake-on-LAN unfortunately.

**Comment by klattimer** [comment]
Wake on LAN is sketchy, there's no method of waking via Wifi on my TV but other people have it working fine. There's also an off state after power cycle which means that WoL can't work yet, but if you power it up and off it does. 

This is a problem with the TV firmware more than anything I think. There's plenty explaining how to manually edit the config file, however this mac address is collected anyway during a scan so not to worry. 

Closing this issue.
